name: 'Docusaurus Release Action'
description: 'Build docusaurus project as part of the build process.'
inputs:
  TAG:
    description: 'Whether to version-tag the docs; usually followed by release'
    default: 'yes' 
    required: false
  VERSION:
    description: "The project version."
    required: false
    default: 0.0.1-test-ci 
  CHANGELOG_FILE:
    description: "File containing the current changelog."
    default: changelog.md
    required: true
  RELEASE_NOTES:
    description: "Path to the release notes file."
    default: ./src/pages/release-notes.md
    required: true
  NPM_REPO:
    description: "The package repo for npm to use."
    required: true
  NPM_TOKEN:
    description: "Token for authenticating with NPM_REPO."
    required: true

runs:
  using: "composite"
  steps: 

    - shell: sh
      if: ${{ inputs.TAG == 'yes' }}
      run: |
        # "Checkout 'release' branch"
        git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
        git fetch --all
        git checkout release

    - shell: bash
      run: |
        # Copy all the templates if on Docusaurus3
        cd docs
        /templates/build-docs.sh --skip-build
        cd ..

    - shell: sh
      run: |
        # "Update npmrc"
        cd docs
        rm -f .npmrc
        echo "@zepben:registry=${{inputs.NPM_REPO}}" >> .npmrc
        echo "//npm.pkg.github.com/:_authToken=${{inputs.NPM_TOKEN}}" >> .npmrc
        # just in case, add EOL
        echo "\n" >> .npmrc

        # fetch dependencies for all flows
        npm ci
        cd ..

    - shell: sh
      if: ${{ inputs.TAG == 'yes' }}
      run: |
        # "VERSION TAG the new documentation"
        cd docs
        npm run docusaurus docs:version ${{ inputs.VERSION }}
        cd ..

    - shell: sh
      if: ${{ inputs.TAG == 'yes' }}
      run: |
        # "Update the release notes
        header="## [${{ inputs.VERSION }}]"
        changelog=$(sed -n -E "/${{ inputs.VERSION }}/,/## [[0-9]+\.[0-9]+\.[0-9]+]/ { /## \[/d;p }" ${{ inputs.CHANGELOG_FILE }})
        to_append="$header\n\n$changelog\n\n---\n"
        cd docs
        flat_version=$(echo ${{ inputs.VERSION }} | sed "s/\.//g")
        sed -i "5i \|\[${{ inputs.VERSION }}\]\(\#v${flat_version}\)\| \`$(date +'%d %B %Y')\` \|" ${{ inputs.RELEASE_NOTES }}
        export ln=$(cat ${{ inputs.RELEASE_NOTES }} | grep -E -n "#+ \[[0-9]+.[0-9]+.[0-9]+" | head -1 | cut -d':' -f1)
        if [ -z "$ln" ]; then
          echo "${changelog}\n\n---\n" >> ${{ inputs.RELEASE_NOTES }}
        else
          awk -v n=$ln -v s="$to_append" 'NR == n {print s} {print}' ${{ inputs.RELEASE_NOTES }} > release-notes.tmp
          mv release-notes.tmp ${{ inputs.RELEASE_NOTES }}
        fi
        cd ..

    - shell: sh
      run: |
        # "Build the documentation site"
        cd docs
        npm run build
        cd ..

    - shell: sh
      if: ${{ inputs.TAG == 'yes' }}
      run: |
        # "Commit the release branch"
        cd docs
        git restore .npmrc
        git add .
        git config user.email "ci.github@zepben.com"
        git config user.name "Github CI"
        git commit -m "Committing doc changes to docusaurus. [skip ci]"
        git push origin release
        cd ..
